### ISSUE TITLE
Error `Decompressing file to`

### ISSUE THREAD

**Issue by tgxn** [LunaMultiplayer/LunaMultiplayerUpdater#7]
![image](https://user-images.githubusercontent.com/293107/124458880-1e7e8700-ddc0-11eb-8c9b-79983a1f6fe5.png)

Looks like it's because i don't have the directory in AppData and this code doesn't check/create it? https://github.com/LunaMultiplayer/LunaMultiplayerUpdater/blob/537b14f5871dbc8e627c3d73ae0144a95664228d/CommonUpdater/Downloader.cs#L43

Not sure how to fix this one.

**Comment by gavazquez** [comment]
Yeah the thing is that the structure of the zip file changed to make it easier for people to install it. I will try to have a look at this and update later

Basically the issue is here:

https://github.com/LunaMultiplayer/LunaMultiplayerUpdater/blob/537b14f5871dbc8e627c3d73ae0144a95664228d/CommonUpdater/Downloader.cs#L84

It should be empty since we don't have a LMPClient folder anymore

**Comment by tgxn** [comment]
Cheers @gavazquez, I've submitted PR #8 which should resolve these issues.
